apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: svc-restart-rules
  namespace: {{ .Release.Namespace }} #observability
  labels:
    rules: alerting
spec:
  groups:

  # Restart Alerts for DB / ArgoCD / Vault
  - name: service-restart-alerts
    rules:
      - alert: VaultRestarted
        expr: increase(kube_pod_container_status_restarts_total{pod=~"vault.*"}[10m]) > 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Vault restarted"
          description: "Vault pod restarted in the last 10 minutes."



