apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: svc-restart-rules
  namespace: observability
  labels:
    rules: alerting
spec:
  groups:
  # Restart Alerts for DB / ArgoCD / Vault
  - name: service-restart-alerts
    rules:
      - alert: DatabaseRestarted
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{pod=~"postgres-db.*"}[5m])) > 0
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Database pod restarted"
          description: "Postgres pod restarted in the last 10 minutes."

      - alert: ArgoCDRestarted
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{pod=~"argocd-server.*"}[5m])) > 0
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "ArgoCD restarted"
          description: "ArgoCD pod restarted in the last 10 minutes."

      - alert: VaultRestarted
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{pod=~"vault.*"}[5m])) > 0
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Vault restarted"
          description: "Vault pod restarted in the last 10 minutes."



