apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: svc-restart-rules
  namespace: {{ .Release.Namespace }} # observability
  labels:
    rules: alerting
spec:
  groups:
  # Restart Alerts for DB / ArgoCD / Vault
  - name: service-restart-alerts
    rules:
      - alert: ArgoCDRestarted
        expr: increase(kube_pod_container_status_restarts_total{pod=~"argocd.*"}[10m]) > 0
        for: 1m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "ArgoCD restarted"
          description: "ArgoCD pod restarted in the last 10 minutes."

     