# TO install ESO use the helm there only define the node selector direcctly for patch 
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: external-secrets
---
# vault-cluster-secretstore.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          serviceAccountRef:
            name: vault-auth
            namespace: external-secrets  # SA in external-secrets namespace
          mountPath: "kubernetes"
          role: "external-secrets-operator"
      caProvider:
        type: Secret
        name: vault-ca
        key: ca.crt
        namespace: external-secrets

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  # Replace with the namespace where you want the secret to be created
  namespace: student-api
spec:
  refreshInterval: "1h" # Syncs the secret every hour
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: db-secrets # The name of the Kubernetes secret to be created
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: database # Path inside the KV engine
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: database
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: database
        property: POSTGRES_DB