apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: svc-restart-rules
  # namespace: observability also check all ns or only observability
  namespace: {{ .Release.Namespace }}
  labels:
    rules: alerting # as per helm Configurations
spec:
  groups:
  # Restart Alerts for DB / ArgoCD / Vault
  - name: service-restart-alerts
    rules:
      - alert: DatabaseRestarted
        expr: increase(kube_pod_container_status_restarts_total{pod=~"postgres.*"}[10m]) > 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Database pod restarted"
          description: "Postgres pod restarted in the last 10 minutes."




