# vault-cluster-secretstore.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          serviceAccountRef:
            name: vault-auth
            namespace: external-secrets  # SA in external-secrets namespace
          mountPath: "kubernetes"
          role: "external-secrets-operator"
      caProvider:
        type: Secret
        name: vault-ca
        key: ca.crt
        namespace: external-secrets