{
 "title": "Application Logs and Metrics",
 "tags": [ "App" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   {
    "name": "log_level",
    "label": "Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{pod=\"$pod\",log_type=\"application\",level=~\"$log_level\"}"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({log_type=\"application\", level=\"ERROR\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Warn Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({log_type=\"application\", level=\"WARNING\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total{http_status=~\"5..\"}[$__rate_interval]))\r\n/\r\n  sum(rate(http_requests_total[$__rate_interval]))\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (\r\n  rate(http_requests_total{\r\n    exported_endpoint=~\"/api/v1/.*\",\r\n  }[$__rate_interval])\r\n)\r\n",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "Latency p90/p95/p99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le)(rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_requests_total{http_status=~\"5..\"}[$__rate_interval]))\r\n/\r\n  sum(rate(http_requests_total[$__rate_interval]))\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of requests by HTTP status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (http_status, pod) (\r\n  rate(http_requests_total{\r\n    exported_endpoint=~\"/api/v1/.*\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Requests by HTTP Method",
   "type": "timeseries",
   "description": "Help identifying Read vs write imbalance",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method)(\r\n  rate(http_requests_total[$__rate_interval])\r\n)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}