apiVersion: v1
kind: Secret
metadata:
  name: grafana-loki-datasources
  namespace: observability
  labels:
    grafana_datasource: 'dynamic' # default value for: sidecar.datasources.label
stringData:
  prom-ds.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki-gateway.observability.svc.cluster.local
        uid: lokidatasource
        access: proxy
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "1"