{
 "title": "New dashboard again",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   {
    "name": "log_level",
    "label": "Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{pod=\"$pod\",log_type=\"application\",level=~\"$log_level\"}"
    }
   ]
  },
  {
   "title": "Latency p90/p95/p99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, pod)(rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*\", pod=~\"$pod\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, pod)(rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*\", pod=~\"$pod\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod)(rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/.*\", pod=~\"$pod\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Error rate (4xx or 5xx)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_status, pod) (\r\n  rate(http_requests_total{\r\n    exported_endpoint=~\"/api/v1/.*\",\r\n    http_status=~\"5..\",\r\n    pod=~\"$pod\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error COUNT ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({pod=\"$pod\", log_type=\"application\", level=\"ERROR\"} [$__range]))"
    }
   ]
  },
  {
   "title": "WARN COUNT ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({pod=\"$pod\", log_type=\"application\", level=\"WARNING\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({pod=\"$pod\", log_type=\"application\", level=~\"$log_level\"}[$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Rate of requests by HTTP status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_status, pod) (\r\n  rate(http_requests_total{\r\n    exported_endpoint=~\"/api/v1/.*\",\r\n    pod=~\"$pod\"\r\n  }[5m])\r\n)",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Total request rate per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(http_requests_total{\r\n    exported_endpoint=~\"/api/v1/.*\",\r\n    pod=~\"$pod\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}